---
baseURL: https://www.vestern.se/

languageCode: en-us
title: Home of Dennis Vesterlund
# theme: toha

module:
  imports:
    - path: github.com/hugo-toha/toha/v4
      disable: false
  mounts:
    - source: ./node_modules/flag-icon-css/flags
      target: static/flags
    - source: ./node_modules/@fontsource/mulish/files
      target: static/files
    - source: ./node_modules/katex/dist/fonts
      target: static/fonts


languages:
  en:
    languageName: English
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - JSON
    - RSS

enableEmoji: true

params:
  background: "images/noomi.jpg"
  gitRepo: https://github.com/tuggan/tuggan.github.io
  gitBranch: main
  logo:
    main: images/logo_fade.png
    inverted: images/logo_fade_bw.png
    favicon: images/logo_fade.png
  features:
    notes:
      enable: true
  enableBlogPost: true
  enableTOC: true
  newsletter:
    enable: false
